---
version: '3.7'

networks:
  backbone:
    external: true

volumes:
  public:
  icons:

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    volumes:
      - ./public/conf.yml:/app/public/conf.yml
      - ./icons/png:/app/public/item-icons
    environment:
      - NODE_ENV=production
    ports:
      - 4000:80
    networks:
      - backbone
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      retries: 3
      start_period: 40s
      timeout: 10s
